import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import PageContainer from "../components/common/PageContainer";
import { ToastProvider } from "@/components/common/Toast/ToastProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <PageContainer>{children}</PageContainer>
        </ToastProvider>
      </body>
    </html>
  );
}
